name: Scrape Osceola County
on:
  schedule:
    - cron: '45 7,13,19,1 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: osceola
      script: python_scrapers/scrapers/run_osceola.py
      args: "--days-back 3"
      needs_xvfb: true
    secrets: inherit
