name: Scrape Sarasota County
on:
  schedule:
    - cron: '5 8,14,20,2 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: sarasota
      script: python_scrapers/scrapers/run_sarasota.py
      args: "1"
      needs_xvfb: true
    secrets: inherit
