name: Scrape Union County
on:
  schedule:
    - cron: '20 */12 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: union
      script: counties/union/runner.py
      args: "--days-back 7"
      needs_xvfb: false
    secrets: inherit
