name: Scrape Orange County
on:
  schedule:
    - cron: '40 7,13,19,1 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: orange
      script: python_scrapers/scrapers/run_orange.py
      args: "1"
      needs_xvfb: true
    secrets: inherit
