name: Scrape Polk County
on:
  schedule:
    - cron: '0 8,14,20,2 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: polk
      script: python_scrapers/scrapers/run_polk.py
      args: "1"
      needs_xvfb: true
    secrets: inherit
