name: Scrape Palm Beach County
on:
  schedule:
    - cron: '50 7,13,19,1 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: palm_beach
      script: python_scrapers/scrapers/run_palm_beach.py
      args: "1"
      needs_xvfb: true
    secrets: inherit
