name: Scrape Seminole County
on:
  schedule:
    - cron: '10 8,14,20,2 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      county: seminole
      script: python_scrapers/scrapers/run_seminole.py
      args: "3"
      needs_xvfb: true
    secrets: inherit
